server:
  port: 8501
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: new-users
          content-type: application/json
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
defaultDepartmentId: "{cipher}a4a502f0ba15cf822cb0451595459ad8c7092e134f4614b66920ee3b47882d7a"