version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  configuration-server:
    image: training/configuration-server
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  discovery-server:
    image: training/discovery-server
    ports:
      - 8089:8089
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  zipkin-server:
    image: training/zipkin-server
    ports:
      - 8090:8090
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  gateway-server:
    image: training/gateway-server
    ports:
      - 8080:8080
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  departments-database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=departments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/departments:/var/lib/postgresql/data/application
  departments:
    image: training/departments
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  users-database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/users:/var/lib/postgresql/data/application
  users:
    image: training/users
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production